server:
  port: 8080
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10
      # 续约到期时间（默认90秒）
      lease-expiration-duration-in-seconds: 30
spring:
  application:
    name: zl-financeservice