package com.meizhuliu.zl.finance.mapper;

import com.meizhuliu.zl.finance.domian.AccountRecordDO;
import com.meizhuliu.zl.finance.domian.AccountRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRecordDOMapper {
    long countByExample(AccountRecordDOExample example);

    int deleteByExample(AccountRecordDOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(AccountRecordDO record);

    int insertSelective(AccountRecordDO record);

    List<AccountRecordDO> selectByExample(AccountRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<AccountRecordDO> selectByExampleSelective(@Param("example") AccountRecordDOExample example, @Param("selective") AccountRecordDO.Column ... selective);

    AccountRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordDO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") AccountRecordDO.Column ... selective);

    int updateByExampleSelective(@Param("record") AccountRecordDO record, @Param("example") AccountRecordDOExample example);

    int updateByExample(@Param("record") AccountRecordDO record, @Param("example") AccountRecordDOExample example);

    int updateByPrimaryKeySelective(AccountRecordDO record);

    int updateByPrimaryKey(AccountRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordDO selectOneByExample(AccountRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordDO selectOneByExampleSelective(@Param("example") AccountRecordDOExample example, @Param("selective") AccountRecordDO.Column ... selective);
}