package com.meizhuliu.zl.finance.mapper;

import com.meizhuliu.zl.finance.domian.AccountRecordAllDO;
import com.meizhuliu.zl.finance.domian.AccountRecordAllDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRecordAllDOMapper {
    long countByExample(AccountRecordAllDOExample example);

    int deleteByExample(AccountRecordAllDOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(AccountRecordAllDO record);

    int insertSelective(AccountRecordAllDO record);

    List<AccountRecordAllDO> selectByExample(AccountRecordAllDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<AccountRecordAllDO> selectByExampleSelective(@Param("example") AccountRecordAllDOExample example, @Param("selective") AccountRecordAllDO.Column ... selective);

    AccountRecordAllDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordAllDO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") AccountRecordAllDO.Column ... selective);

    int updateByExampleSelective(@Param("record") AccountRecordAllDO record, @Param("example") AccountRecordAllDOExample example);

    int updateByExample(@Param("record") AccountRecordAllDO record, @Param("example") AccountRecordAllDOExample example);

    int updateByPrimaryKeySelective(AccountRecordAllDO record);

    int updateByPrimaryKey(AccountRecordAllDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordAllDO selectOneByExample(AccountRecordAllDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_record_all
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AccountRecordAllDO selectOneByExampleSelective(@Param("example") AccountRecordAllDOExample example, @Param("selective") AccountRecordAllDO.Column ... selective);
}