package com.meizhuliu.zl.finance.mapper;

import com.meizhuliu.zl.finance.domian.UserAccountDetailDO;
import com.meizhuliu.zl.finance.domian.UserAccountDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountDetailDOMapper {
    long countByExample(UserAccountDetailDOExample example);

    int deleteByExample(UserAccountDetailDOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserAccountDetailDO record);

    int insertSelective(UserAccountDetailDO record);

    List<UserAccountDetailDO> selectByExample(UserAccountDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserAccountDetailDO> selectByExampleSelective(@Param("example") UserAccountDetailDOExample example, @Param("selective") UserAccountDetailDO.Column ... selective);

    UserAccountDetailDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAccountDetailDO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") UserAccountDetailDO.Column ... selective);

    int updateByExampleSelective(@Param("record") UserAccountDetailDO record, @Param("example") UserAccountDetailDOExample example);

    int updateByExample(@Param("record") UserAccountDetailDO record, @Param("example") UserAccountDetailDOExample example);

    int updateByPrimaryKeySelective(UserAccountDetailDO record);

    int updateByPrimaryKey(UserAccountDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAccountDetailDO selectOneByExample(UserAccountDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAccountDetailDO selectOneByExampleSelective(@Param("example") UserAccountDetailDOExample example, @Param("selective") UserAccountDetailDO.Column ... selective);
}