package com.meizhuliu.zl.finance.mapper;

import com.meizhuliu.zl.finance.domian.UserGiftsDO;
import com.meizhuliu.zl.finance.domian.UserGiftsDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGiftsDOMapper {
    long countByExample(UserGiftsDOExample example);

    int deleteByExample(UserGiftsDOExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserGiftsDO record);

    int insertSelective(UserGiftsDO record);

    List<UserGiftsDO> selectByExample(UserGiftsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gifts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserGiftsDO> selectByExampleSelective(@Param("example") UserGiftsDOExample example, @Param("selective") UserGiftsDO.Column ... selective);

    UserGiftsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gifts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserGiftsDO selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") UserGiftsDO.Column ... selective);

    int updateByExampleSelective(@Param("record") UserGiftsDO record, @Param("example") UserGiftsDOExample example);

    int updateByExample(@Param("record") UserGiftsDO record, @Param("example") UserGiftsDOExample example);

    int updateByPrimaryKeySelective(UserGiftsDO record);

    int updateByPrimaryKey(UserGiftsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gifts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserGiftsDO selectOneByExample(UserGiftsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gifts
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserGiftsDO selectOneByExampleSelective(@Param("example") UserGiftsDOExample example, @Param("selective") UserGiftsDO.Column ... selective);
}